library( ez); library( ggplot2); library( nlme); library( pastecs); library( reshape); library( WRS2)

# standard contrast (Phase1vs2 and Phase1vs3)
Phase1vs2 <- c(0,1,0)
Phase1vs3 <- c(0,0,1)
contrasts(squeezeData$Phase)<-cbind(Phase1vs2,Phase1vs3)

baselineActiveTime1 <- lme(ActiveTime ~ 1, random = ~1|Sub/Phase, data = squeezeData, method = "ML")
phaseActiveTime1 <- update(baselineActiveTime1, .~. + Phase)
groupActiveTime1 <- update(phaseActiveTime1, .~. + Group)
phase_group_ActiveTime1 <- update(groupActiveTime1, .~. + Phase:Group)
anova(baselineActiveTime1, phaseActiveTime1, groupActiveTime1, phase_group_ActiveTime1)
summary(phase_group_ActiveTime1)
by(squeezeData$ActiveTime, list(squeezeData$Phase),stat.desc,basic = FALSE)
by(squeezeData$ActiveTime, list(squeezeData$Group),stat.desc,basic = FALSE)

# new contrasts (Phase2vs1 and Phase2vs3)
Phase2vs1 <- c(1,0,0)
Phase2vs3 <- c(0,0,1)
contrasts(squeezeData$Phase)<-cbind(Phase2vs1,Phase2vs3)

baselineActiveTime2 <- lme(ActiveTime ~ 1, random = ~1|Sub/Phase, data = squeezeData, method = "ML")
phaseActiveTime2 <- update(baselineActiveTime2, .~. + Phase)
groupActiveTime2 <- update(phaseActiveTime2, .~. + Group)
phase_group_ActiveTime2 <- update(groupActiveTime2, .~. + Phase:Group)
anova(baselineActiveTime2, phaseActiveTime2, groupActiveTime2, phase_group_ActiveTime2)
summary(phase_group_ActiveTime2)
by(squeezeData$ActiveTime, list(squeezeData$Phase),stat.desc,basic = FALSE)
by(squeezeData$ActiveTime, list(squeezeData$Group),stat.desc,basic = FALSE)