squeezeData <- read.csv("SqueezeDataR.dat", sep = ',',header = TRUE, na.strings = 'NaN')
squeezeData$Group <- factor(squeezeData$Group)
#squeezeData$Trial <- factor(squeezeData$Trial)
squeezeData$Haptic <- factor(squeezeData$Haptic)
squeezeData$Phase <- factor(squeezeData$Phase)

library( ez); library( ggplot2); library( nlme); library( pastecs); library( reshape); library( WRS2)

# standard contrast (Phase1vs2 and Phase1vs3)
Phase1vs2 <- c(0,1,0)
Phase1vs3 <- c(0,0,1)
contrasts(squeezeData$Phase)<-cbind(Phase1vs2,Phase1vs3)

baselineInt1 <- lme(IntMag ~ 1, random = ~1|Sub/Phase, data = squeezeData, na.action=na.omit, method = "ML")
phaseInt1 <- update(baselineInt1, .~. + Phase)
groupInt1 <- update(phaseInt1, .~. + Group)
phase_group_Int1 <- update(groupInt1, .~. + Phase:Group)
anova(baselineInt1, phaseInt1, groupInt1, phase_group_Int1)
summary(phase_group_Int1)
by(squeezeData$IntMag, list(squeezeData$Phase,squeezeData$Group),stat.desc,basic = FALSE)
#by(squeezeData$IntMag, list(squeezeData$Group),stat.desc,basic = FALSE)

# new contrasts (Phase2vs1 and Phase2vs3)
Phase2vs1 <- c(1,0,0)
Phase2vs3 <- c(0,0,1)
contrasts(squeezeData$Phase)<-cbind(Phase2vs1,Phase2vs3)

baselineInt2 <- lme(IntMag ~ 1, random = ~1|Sub/Phase, data = squeezeData, na.action=na.omit, method = "ML")
phaseInt2 <- update(baselineInt2, .~. + Phase)
groupInt2 <- update(phaseInt2, .~. + Group)
phase_group_Int2 <- update(groupInt2, .~. + Phase:Group)
anova(baselineInt2, phaseInt2, groupInt2, phase_group_Int2)
summary(phase_group_Int2)
by(squeezeData$IntMag, list(squeezeData$Phase,squeezeData$Group),stat.desc,basic = FALSE)
#by(squeezeData$IntMag, list(squeezeData$Group),stat.desc,basic = FALSE)