library( ez); library( ggplot2); library( nlme); library( pastecs); library( reshape); library( WRS2)

# standard contrast (Phase1vs2 and Phase1vs3)
Phase1vs2 <- c(0,1,0)
Phase1vs3 <- c(0,0,1)
contrasts(squeezeData$Phase)<-cbind(Phase1vs2,Phase1vs3)

baselineMean1 <- lme(MeanMag ~ 1, random = ~1|Sub/Phase, data = squeezeData, method = "ML")
phaseMean1 <- update(baselineMean1, .~. + Phase)
groupMean1 <- update(phaseMean1, .~. + Group)
phase_group_mean1 <- update(groupMean1, .~. + Phase:Group)
anova(baselineMean1, phaseMean1, groupMean1, phase_group_mean1)
summary(phase_group_mean1)
by(squeezeData$MeanMag, list(squeezeData$Phase),stat.desc,basic = FALSE)
by(squeezeData$MeanMag, list(squeezeData$Group),stat.desc,basic = FALSE)

# new contrasts (Phase2vs1 and Phase2vs3)
Phase2vs1 <- c(1,0,0)
Phase2vs3 <- c(0,0,1)
contrasts(squeezeData$Phase)<-cbind(Phase2vs1,Phase2vs3)

baselineMean2 <- lme(MeanMag ~ 1, random = ~1|Sub/Phase, data = squeezeData, method = "ML")
phaseMean2 <- update(baselineMean2, .~. + Phase)
groupMean2 <- update(phaseMean2, .~. + Group)
phase_group_mean2 <- update(groupMean2, .~. + Phase:Group)
anova(baselineMean2, phaseMean2, groupMean2, phase_group_mean2)
summary(phase_group_mean2)
by(squeezeData$MeanMag, list(squeezeData$Phase),stat.desc,basic = FALSE)
by(squeezeData$MeanMag, list(squeezeData$Group),stat.desc,basic = FALSE)