library( ez); library( ggplot2); library( nlme); library( pastecs); library( reshape); library( WRS2)

# standard contrast (Phase1vs2 and Phase1vs3)
Phase1vs2 <- c(0,1,0)
Phase1vs3 <- c(0,0,1)
contrasts(squeezeData$Phase)<-cbind(Phase1vs2,Phase1vs3)

baselineRms1 <- lme(RmsMag ~ 1, random = ~1|Sub/Phase, data = squeezeData, method = "ML")
phaseRms1 <- update(baselineRms1, .~. + Phase)
groupRms1 <- update(phaseRms1, .~. + Group)
phase_group_Rms1 <- update(groupRms1, .~. + Phase:Group)
anova(baselineRms1, phaseRms1, groupRms1, phase_group_Rms1)
summary(phase_group_Rms1)
by(squeezeData$RmsMag, list(squeezeData$Phase),stat.desc,basic = FALSE)
by(squeezeData$RmsMag, list(squeezeData$Group),stat.desc,basic = FALSE)

# new contrasts (Phase2vs1 and Phase2vs3)
Phase2vs1 <- c(1,0,0)
Phase2vs3 <- c(0,0,1)
contrasts(squeezeData$Phase)<-cbind(Phase2vs1,Phase2vs3)

baselineRms2 <- lme(RmsMag ~ 1, random = ~1|Sub/Phase, data = squeezeData, method = "ML")
phaseRms2 <- update(baselineRms2, .~. + Phase)
groupRms2 <- update(phaseRms2, .~. + Group)
phase_group_Rms2 <- update(groupRms2, .~. + Phase:Group)
anova(baselineRms2, phaseRms2, groupRms2, phase_group_Rms2)
summary(phase_group_Rms2)
by(squeezeData$RmsMag, list(squeezeData$Phase),stat.desc,basic = FALSE)
by(squeezeData$RmsMag, list(squeezeData$Group),stat.desc,basic = FALSE)