squeezeData <- read.csv("SqueezeDataR.dat", sep = ',',header = TRUE, na.strings = 'NaN')
squeezeData$Group <- factor(squeezeData$Group)
#squeezeData$Trial <- factor(squeezeData$Trial)
squeezeData$Haptic <- factor(squeezeData$Haptic)
squeezeData$Phase <- factor(squeezeData$Phase)

library( ez); library( ggplot2); library( nlme); library( pastecs); library( reshape); library( WRS2)

# standard contrast (Phase1vs2 and Phase1vs3)
Phase1vs2 <- c(0,1,0)
Phase1vs3 <- c(0,0,1)
contrasts(squeezeData$Phase)<-cbind(Phase1vs2,Phase1vs3)

baselineTime1 <- lme(Time ~ 1, random = ~1|Sub/Phase, data = squeezeData, na.action=na.omit, method = "ML")
phaseTime1 <- update(baselineTime1, .~. + Phase)
groupTime1 <- update(phaseTime1, .~. + Group)
phase_group_Time1 <- update(groupTime1, .~. + Phase:Group)
anova(baselineTime1, phaseTime1, groupTime1, phase_group_Time1)
summary(phase_group_Time1)
by(squeezeData$Time, list(squeezeData$Phase,squeezeData$Group),stat.desc,basic = FALSE)
#by(squeezeData$Time, list(squeezeData$Group),stat.desc,basic = FALSE)

# new contrasts (Phase2vs1 and Phase2vs3)
Phase2vs1 <- c(1,0,0)
Phase2vs3 <- c(0,0,1)
contrasts(squeezeData$Phase)<-cbind(Phase2vs1,Phase2vs3)

baselineTime2 <- lme(Time ~ 1, random = ~1|Sub/Phase, data = squeezeData, na.action=na.omit, method = "ML")
phaseTime2 <- update(baselineTime2, .~. + Phase)
groupTime2 <- update(phaseTime2, .~. + Group)
phase_group_Time2 <- update(groupTime2, .~. + Phase:Group)
anova(baselineTime2, phaseTime2, groupTime2, phase_group_Time2)
summary(phase_group_Time2)
by(squeezeData$Time, list(squeezeData$Phase,squeezeData$Group),stat.desc,basic = FALSE)
#by(squeezeData$Time, list(squeezeData$Group),stat.desc,basic = FALSE)